# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: muhamadriyadi524@gmail.com
author_name: Muhamad Riyadi
cloud_provider: none
contract_name: Fullstackcoba
preset_name: production
project_name: Fullstackcoba1

